module.exports = {
    env: {
        REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
        REACT_APP_FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
        REACT_APP_PROJECT_ID: process.env.REACT_APP_PROJECT_ID,
        REACT_APP_STORAGE_BUCKET: process.env.REACT_APP_STORAGE_BUCKET,
        REACT_APP_MESSAGE_SENDER_ID: process.env.REACT_APP_MESSAGE_SENDER_ID,
        REACT_APP_APP_ID: process.env.REACT_APP_APP_ID,
        REACT_APP_MEASUREMENT_ID: process.env.REACT_APP_MEASUREMENT_ID,
        REACT_APP_GOOGLE_AUTH_DOMAIN: process.env.REACT_APP_GOOGLE_AUTH_DOMAIN,
        REACT_APP_BACKEND_URL: process.env.REACT_APP_BACKEND_URL,
    },
};
